name: Workflow deploiement basic d'un cluster AKS
on:
  push:
    branches:
    - master
    path:
    - Applications

jobs:
  build-and-deploy:
    name: deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script Creation d'un "RG"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.0
        inlineScript: |
          az group create --name RG-AKS-000-Basic --location eastus2