name: Workflow deploiement basic d'un cluster AKS
on:
  push:
    branches:
    - master
    path:
    - Applications

jobs:
  build-and-deploy:
    name: deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script Creation d'un "RG"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.0
        inlineScript: |
          az group create --name RG-AKS-000-Basic --location eastus2

    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Azure - Login ARM
      uses: Azure/github-actions/login@master
      env:
        AZURE_SUBSCRIPTION: Peter_Azure
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}

    - name: Azure - Deploy ARM Template
      uses: Azure/github-actions/arm@master
      env:
        AZURE_RESOURCE_GROUP: RG-AKS-000-Basic
        AZURE_TEMPLATE_LOCATION: ./Basic/ARM/azuredeploy.json
        AZURE_TEMPLATE_PARAM_LOCATION: ./Basic/ARM/azuredeploy.parameters.json

    - name: Connection au Cluster
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: "RG-AKS-000-Basic"
        cluster-name: "Clust-AKS-000"
      id: login

    - name: Installation manifest
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          ./Applications/azure-vote.yml
      kubectl-version: "latest"